#!/bin/bash
# List Available Scripts
# This shell script lists all available scripts and their purposes

echo "Available Scripts for GitHub PR Analyzer"
echo "======================================="
echo ""
echo "Quick Start:"
echo "-----------"
echo "./run_all.sh your_github_token_here"
echo "  - All-in-one script: sets token, verifies it, and runs analysis"
echo ""
echo "Token Management:"
echo "---------------"
echo "./set_permanent_token_unix.sh your_github_token_here"
echo "  - Sets GITHUB_TOKEN environment variable permanently in your shell profile"
echo ""
echo "./set_github_token.sh your_github_token_here"
echo "  - Sets GITHUB_TOKEN for current session and runs analysis"
echo ""
echo "./check_token.sh"
echo "  - Verifies if GITHUB_TOKEN is set and valid"
echo ""
echo "Analysis:"
echo "--------"
echo "./analyze_trending_java.sh [your_github_token_here]"
echo "  - Analyzes top 10 trending Java projects on GitHub"
echo "  - Token is optional if GITHUB_TOKEN environment variable is set"
echo ""
echo "Python Scripts:"
echo "-------------"
echo "python3 find_trending_java_projects.py [--token TOKEN] [--limit LIMIT]"
echo "  - Main script to find and analyze trending Java projects"
echo ""
echo "python3 check_github_token.py"
echo "  - Checks if GITHUB_TOKEN is set and valid"
echo ""
echo "python3 github_pr_analyzer.py owner/repo [--token TOKEN] [--output FILE] [--limit LIMIT]"
echo "  - Analyzes a specific GitHub repository for PRs"
